### ISSUE TITLE
Aenea Dictation Client keystroke errors with OS X server

### ISSUE THREAD

**Issue by seananderson** [dictation-toolbox/aenea#118]
Thank you for creating and maintaining this excellent set of tools. I'm excited to get back to programming after many months of RSI. 

I have everything working with a Windows 10 client and OS X 10.11.3 server except that I'm having trouble with the Aenea Dictation Client.

With the current code, when I start capturing dictation with the Aenea Dictation Client I get the error:

```
ProtocolError: (-32603, u'Server error:   File "server_osx.py", line 414, in key_press | RuntimeError: Don\'t know how to handle keystroke Control_R')
```

I assume the purpose of pressing control is to test that the client is working. If I comment out [line 74 of `aenea_client.py`](https://github.com/dictation-toolbox/aenea/blob/master/client/aenea_client.py#L74) then dictation is captured and transferred to the OS X server until a key outside of `LITERAL_KEYS` is pressed, say through a command from a grammar. Then I get errors such as:

```
ProtocolError: (-32603, u'Server error:   File "server_osx.py", line 414, in key_press | RuntimeError: Don\'t know how to handle keystroke Num_Lock')
```

or

```
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "server_osx.py", line 414, in key_press | RuntimeError: Don\'t know how to handle keystroke ctrl')
```

And dictation no longer transfers from the client to server until I restart Dragon on Windows and restart the Aenea Dictation Client.

I assume this is a problem with key translation. Is there a way that I can fix this so that it works with the OS X server?

Here's a full traceback:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "aenea_client.py", line 217, in start_capture
    self.proxy_buffer.start_capture()
  File "aenea_client.py", line 74, in start_capture
    aenea.ProxyKey('Control_R').execute()
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 127, in execute
    if self._execute(data) == False:
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 179, in _execute
    self._execute_events(self._events)
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_actions.py", line 130, in _execute_events
    aenea.communications.server.execute_batch(commands)
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 100, in execute_batch
    self._execute_batch(batch, aenea.config.USE_MULTIPLE_ACTIONS)
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 87, in _execute_batch
    batch[0][0])(*batch[0][1], **batch[0][2])
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 290, in __call__
    return self.__send(self.__name, kwargs)
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
ProtocolError: (-32603, u'Server error:   File "server_osx.py", line 414, in key_press | RuntimeError: Don\'t know how to handle keystroke Control_R')
```

**Comment by calmofthestorm** [comment]
Sorry about the delay. I believe we added that Control_R way back to deal with VirtualBox capture. The best option there is to comment that out when on OS X.

As to the other issues, this seems to be a reflection of #65. The best option is probably to add some logic in the OS X server to translate keystrokes as appropriate, and/or to modify the relevant grammars to send keys OS X understands.

I don't use OS X or have an install handy so I'm unlikely to do this, but I'm happy to accept PRs to this effect.

**Comment by dylan-chong** [comment]
Commenting out the if ... raise ... lines seems to work

**Comment by seananderson** [comment]
Yes, commenting that out works. 

Separately, I've been using this full-time for over a year now on OS X / macOS. So first, this project has saved my career, *thank you*. I can't thank everyone who's worked on this enough. 

I don't know if anyone else is using the OS X functionality but I've had to make a number of small changes for it to work.

If the current version is working for others then that's great and carry on, but if you would like the changes then I am happy to make a pull request. This is working on 2 separate computers for me. Previously with 10.11 and now with the latest 10.12.5 (macOS Sierra). 

My fork is here: https://github.com/seananderson/aenea

Diff: https://github.com/dictation-toolbox/aenea/compare/master...seananderson:master

The major changes are:
- fix some key names and key translations
- switch from pasting Text() to simulating keypresses. This is a bit slower but much more functional for me because it lets me type everywhere that I could type with the keyboard. For example, you can't type in the Vim command line with paste and some input forms on websites or application dialog boxes don't allow you to paste. Also, some programs, like MS Word, do weird things with spaces at the end if you paste. Plus, using copy and paste constantly clobbers the clipboard. Recently I had to add a micro pause between keypresses after an operating system update or the typing would sometimes be too fast and letters would be lost. 
- a recent addition that you may not want merged is the ability to execute arbitrary macros with the program Keyboard Maestro by checking if a Text() command starts with "KBM " and then executing the macro by that name. I use that for all sorts of things including application launching and window positioning. I'm sure there's a more elegant way to do this.

(For anyone stumbling on this later, I started adding those macros [here](https://github.com/seananderson/kbm-macros) and my grammar files are [here](https://github.com/seananderson/aenea-grammars). They are a mess but they work for me. I also use SmartNav for head tracking and the Kinesis Savant foot pedals for dragging / some clicking.)

**Comment by dylan-chong** [comment]
That looks awesome! I'm gonna try your stuff out.

I suppose is this is a pull request, it kinda belongs in the pull request section (I'm not a contributor to the project btw)

**Comment by sweetmandm** [comment]
💯 I also had to put in a fix for: "Switch from pasting Text() to simulating keypresses". I didn't want to mess with AppleScript so I just pulled in pyautogui:
https://github.com/sweetmandm/aenea/commit/9bf65c6c3e341a8daebe0d4c973d3e37caf5cc80
