### ISSUE TITLE
Install requirements with pip

### ISSUE THREAD

**Issue by kevinsimper** [dictation-toolbox/aenea#120]
Would it be an idea to have an requirements.txt and then you could install with pip?

**Comment by calmofthestorm** [comment]
I added requirements.txt for the client and linux/os x servers (the windows server uses Cabal). Unfortunately I don't think it's practical to do a full install with pip -- the client depends on a lot of non-free software (dragon), and things that aren't themselves available via pip (natilnk). But this will at least let people install those requirements that are available with pip easily.

We might be able to do the server via pip. The only major snag is it depends on xdotool but that's going away with #105 and being replaced with a Python library. At any rate there's likely a way to get that installed via pip.

There would be some other changes needed as well to package this into something that you can just install and run -- figuring out where to put config files, etc. Nothing too hard, but it would need to be done.

**Comment by kevinsimper** [comment]
Cool, it also makes it easier if there is new updates to Aenea!
