### ISSUE TITLE
Grammer does not get loaded

### ISSUE THREAD

**Issue by kevinsimper** [dictation-toolbox/aenea#123]
I changed my project_root to a virtualbox share folder, but the grammers does not get loaded. They do if they are in the MacroSystem folder.

I searched the issues and did not find anything about it.

How do you organize your grammars? :)

**Comment by calmofthestorm** [comment]
Grammars are unaffected by project root, since they are loaded by Natlink and project_root is an aenea specific setting for its configuration and state storage. I think most people just keep their config in MacroSystem.
