### ISSUE TITLE
Socket error connecting to aenea server

### ISSUE THREAD

**Issue by lisgie** [dictation-toolbox/aenea#125]
First of all, thanks for this awesome project, I highly appreciate the work and the throrough documentation!

I basically completed all the steps of the short tutorial and the host-only adapter has been set up and can be pinged from the Guest as well as the Host (aenea.json and config.py have been adapted with the same IP accordingly). However, when I try to start DNS with, I get the following error:

_Socket error connecting to aenea server. To avoid slowing dictation, we won't try again for 5 seconds._

It makes tracking down the point of failure quite hard since everything else seems to work fine.

Does anyone have an idea?

Thanks a lot in advance!

**Comment by mzizzi** [comment]
The aenea client can't connect to your aenea server for some reason.

Possible causes:
* Aenea client itself is misconfigured (aenea.json in the dragonfly macro folder)
* Aenea server isn't listening on the right interface (config.py must be set to use the ip for the host only adapter)

**Comment by lisgie** [comment]
Thanks mzizzi, got it finally working now.

The mistake was rather silly. Windows hides file extensions by default, so _aenea.json_ (as displayed in the folder structure) was actually _aenea.json.example_.

**Comment by dylan-chong** [comment]
i also found that `MacroSystem/server_state.json` contained `{"host": "localhost", "port": 8240}` instead of `{"host": "192.168.56.1", "port": 8240}` which works

**Comment by dylan-chong** [comment]
if this issue is solved can it be closed ? @lisgie

**Comment by sparkvilla** [comment]
Hi there, I have the same issue. 
my Host = ubuntu 18.04
my Guest = Windows 7

`aenea.json`on the client = 
```
{ host = "192.168.56.1", "port": 8240, platform: "proxy", "use_multiple_actions": true, "screen_resolution": [6400, 1440], "project_root": "C:\\Natlink\Natlink\MacroSystem", "restrict_proxy_to_aenea_client": false}
```
`config.py` on the server =
```
# Host-side config (Linux host receiving commands)
HOST = "192.168.56.1"
PORT = 8240

PLUGIN_PATH = ["plugins"]
ENABLE_XSEL = False
XDOTOOL_DELAY = 0 
```
When I execute `_hello_world_aenea.py` with the voice command and I get `Socket error connecting to aenea server. To avoid slowing dictation, we won't try again for 5 seconds.`  from Natlink Messages..Any help??

**Comment by Danesprite** [comment]
Hello @sparkvilla. Let's see if I can help you with this.

Have you set up a host-only adapter for your Windows 7 VM? You can do that in the VirtualBox preferences under 'Network->Host-only Networks'. You also need to set it up in the VM settings under 'Network'.

If you have already set that up, then maybe it is a firewall issue? Try checking that you can ping the host machine from the guest machine and vice versa by running something like:

`ping 192.168.56.101`

**Comment by sparkvilla** [comment]
Hi @Danesprite and thanks for your help. It is now actually working! I can run the `_hello_world_aenea.py` and see on my host `Aenea remote setup operational`! I had a `NetlinkUserdirectory` that did not have the `aenea.json`. Just by adding such a file in there.. voilà it works!! Thanks for this fantastic tool.

**Comment by dylan-chong** [comment]
Hey Diego, thanks for responding with your solution. Is there anything in the README that could be clarified?

**Comment by sparkvilla** [comment]
Hi @dylan-chong. I think it would be good to mention that the aenea.json file should be present also in a user defined directory beside the MacroSystem directory. Because of that my setup was not working..

**Comment by Danesprite** [comment]
@sparkvilla I'm glad you got it all working! :+1:

@dylan-chong Thank you for the pull request. I'm sure Alex will get to it soon enough, he's probably just busy.
