### ISSUE TITLE
Key("control:down") not working

### ISSUE THREAD

**Issue by tbenst** [dictation-toolbox/aenea#128]
Aenea is super slick, thanks again for releasing this!

I see that Key("c:down").execute() works but repeats 'c'. I have been unable to get control:down to work, although perhaps I'm not trying the right keyword (this is the word for Dragonfly).

Let me know your thoughts? Thanks!

**Comment by tbenst** [comment]
I found a solution, for posterity. Aenea has very similar but slightly different key bindings than dragonfly. "ctrl" must be used instead.

**Comment by calmofthestorm** [comment]
It was my intent to have it support all the keys that Dragonfly does, so that grammars can be used interchangeably with as little changes as possible. So this is a bug.

**Comment by nirvdrum** [comment]
I don't think this is a bug in Aenea. It's just a slight quirk in Dragonfly. I recently got bit by it as well, but upon further reflection it makes sense. The short-hand 'c' is only used as a modifier and thus needs to be used in a combo of some sort (e.g., 'c-f'). Outside of a combination, you need to be able to press the literal character 'c' and that's what `Key("c")` does. The `:down` is then applied to that key, naturally enough. For the non-combo cases, you need to use the key name as listed in the [dragonfly docs](http://pythonhosted.org//dragonfly/actions.html#key-action).

NB: 'w' is listed as a modifier, but appears in the special keys list, not the modifier keys list. But it follows the same rules as the other modifiers.

**Comment by calmofthestorm** [comment]
Hmmm good point.
