### ISSUE TITLE
Is anybody using Aenea on Windows 10 ?

### ISSUE THREAD

**Issue by shivshankark** [dictation-toolbox/aenea#146]
I have been happily using Aenea since last couple of months. This week I received an email from my IT department saying that I need to upgrade to Windows 10. 

I went through the documentation and found the note below :| -
> NatLink has some problems on Windows 10 64-bit related to the msvcr100.dll file. It is unclear whether it is the 64-bit or the Windows 10 which resulted in the problem. Therefore it is recommended that you use the version of Windows mentioned above.

I was curious to know if anyone has successfully used Aenea on windows 10 ?

**Comment by calmofthestorm** [comment]
@dylan-chong added that warning, so perhaps they can go into more detail. Are you running Aenea in a VM or on a physical machine? If it's on a VM and working fine, you could consider just disabling the VM's ability to connect to the network and ignoring IT; they'd have no way of knowing:-)

**Comment by shivshankark** [comment]
I am running Aenea on VM but I could not get it to work with host-only adapter, so I switched to NAT. Right now I am installing Win10 besides Win7, I will keep the thread posted with my results.

**Comment by dylan-chong** [comment]
What could you not get to work? Also are you running 32 bit windows 7 on the VM?

**Comment by shivshankark** [comment]
@dylan-chong I am on 64 bit windows 7. For me, the client could not telnet to host only IP

**Comment by shivshankark** [comment]
@dylan-chong Aside - what was the issue you faced on Win 10 for which you added the warning mentioned above?

**Comment by dylan-chong** [comment]
I've never used telnet before, but from googling it, it appears to be a 2 way protocol. Perhaps the host-only adapter only allows for one way communication. What part of the setup stage are you on?

I tried to install Natlink and from (2 months old, unreliable) memory, Natlink would not open successfully when starting up Dragon, either that or I could not enable natlink through the 'Configoure NatLink via command line interface / GUI' program.

**Comment by calmofthestorm** [comment]
I suspect a misconfiguration is more likely; I use a host only adapter and traffic goes both ways, provided the connection is initiated on the client (in the VM). What VM software are you using? I've mostly used VirtualBox.

**Comment by shivshankark** [comment]
@calmofthestorm  I am using VirtulaBox. With host only adapter, I can ping the ip 192.168.56.1 but can not telnet on port 8240 from VM (screenshot attached below). I also tried to add explicit firewall rule, but no luck. Interestingly, things work with NAT so I am functional with windows 7.

I just finished installing windows 10. I will try to complete rest of the setup by early next week and keep the thread updated with findings.

![aenea host only adapter connection issue](https://user-images.githubusercontent.com/8355118/27983039-48e9e07e-6368-11e7-8e0c-71858035841e.png)

**Comment by shivshankark** [comment]
I finally got a chance to proceed on this thread today. I found that Dragon 13 does not start on my Windows 10. I see an error in event log reporting fault. I could not get any leads with google search yet. I will probably have to reach Nuance customer support and see if they can help.

Let me know if anyone here has a clue.

![dragon launch error](https://user-images.githubusercontent.com/8355118/28243648-56a3895c-6987-11e7-93b0-198eb3965fc3.png)

**Comment by shivshankark** [comment]
Latest status - I could not get Dragon launch on Windows 10 at all. I am not going to install it on Win7 and then upgrade operating system to windows 10.

**Comment by calmofthestorm** [comment]
Thank you for the updates! Sorry I don't have much advice.

**Comment by shivshankark** [comment]
Finally I got a chance to proceed on this thread. Just today I tested that after upgrading to windows 10 from a working windows 7 Aenea set up, everything works fine. I'm happy with this workaround, for now.

Closing this issue, but I'll still be interested to know if anybody can get Dragon 13 work on fresh copy of windows 10.
