### ISSUE TITLE
Support for accentuated letters is lacking

### ISSUE THREAD

**Issue by lots-of-birds** [dictation-toolbox/aenea#156]
Hello there.
Current setup with Dragon 14 with a french profile, natlink Uniform, and the last version of dragonFly patched to accept accentuated letters
(made possible by the manual application of the patch given by chep in [this thread](https://github.com/t4ngo/dragonfly/issues/11))

All is working fine , even in french, as long as I don't use words with accentuated letters, ("être", "coupé", "lève", ...)

In my setup Natlink and dragonfly handles it well, but not aena.

The error brought back by natlink is (this is only the last line for clarity, full error at the end of post): 
`jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/remi/aenea-master/server/linux_x11/x11_xdotool.py", line 178, in write_command | UnicodeEncodeError: \'ascii\' codec can\'t encode character u\'\\xe9\' in position 3: ordinal not in range(128)')`

this corresponds to this piece of code from aenea-master/server/linux_x11/x11_xdotool.py : 
```
    def write_command(self, message, arguments='type --file -',
                      executable=None):
        executable = executable or self.xdotool
        self.logger.debug(
                'echo \'%s\' | %s %s' % (message, executable, arguments))
        with os.popen('%s %s' % (executable, arguments), 'w') as fd:
            fd.write(message) # THIS IS LINE 186
```

The debug line puts properly the accentuated letters on my terminal : 
`echo 'coupé' | xdotool type --file - --delay 0`
But doesn't then execute anything

Of course, if I copy-paste this very line into a terminal, is executes properly and without any problem.
It seems the execution environment launched from python somehow doesn't support utf-8. 
Anybody as a clue as how to get to the next step ?

**Comment by calmofthestorm** [comment]
Fixed in #157.
