### ISSUE TITLE
Plugin-based chaining grammars

### ISSUE THREAD

**Issue by calmofthestorm** [dictation-toolbox/aenea#19]
Grammars such as multiedit and verbal_emacs work by building up a bunch of commands, each of which the user would think of as a single command, and then creating a repetition rule. This allows the user to string together commands, rather than having to wait for each to be recognized before speaking the next (or at the very least without pausing between commands). To Dragon, this looks like one large command each time the user speaks.

This is great for usability, and it is wonderful that Dragon can support such complicated commands. I would argue that it is the capability of doing this alone that makes editing text possible in this way. Unfortunately, this tends to lead to conflating the natural concept of a command from a users perspective with the logic necessary to support the chaining. This leads to issues such as the duplication of code between verbal_emacs and multiedit. As the project grows, and more people want to use different languages, different programs, etc., I feel like this architecture will become more and more unwieldy.

I propose the following as a long-term design for how to solve this. I basically see three distinct problems that need to be composed in various combinations to make any particular grammar along the lines of verbal_emacs, multiedit, shell commands, etc:
- The actual logic of chaining (take a list of commands, put them together in a repetition rule, delegate the actual command processing as appropriate). You can also think of this as the interface to dragonfly/natlink.
- Various "plug-ins" that each constitute a family of commands. Examples of this include the variable name formatting functions in multiedit and verbal_emacs, shell functionality such as pipes and redirects, editing commands in VIM, and the Python-specific and Eclipse-specific commands in multiedit.
- The tie together that determines which plug-ins should be enabled in which contexts, possibly also with some glue logic (such as managing the mode you are in in VIM). This could possibly also integrate with the work in https://github.com/poppe1219/dragonfly-scripts/tree/master/dynamics to allow dynamic loading of plug-ins as appropriate.

This is how I would build this in the absence of constraints. Unfortunately I need to look into what constraints Natlink/Dragonfly/Dragon impose (in particular I suspect some of the issues with nested grammars being thrown out for being too complex that I ran into with verbal_emacs will likely reappear here; Dragon seems to object more to grammars that are too deep (even when unambiguous) then to grammars which recognize a large number of commands, which is what I would expect based on how most parsing tends to go) and I suspect that is likely to dominate the design, unfortunately.

This is also complicated by #17.

I welcome feedback, both on my design in ideal land and on the realities anyone has run into with similar projects. @poppe1219 @nirvdrum

**Comment by jgarvin** [comment]
I've been on rolling my own server/client to use Dragon on Linux (I started my project before I know about aenea) and stumbled on this thread trying to find if anyone knew the exact conditions that trigger natlink.BadGrammar complaining about the grammar being too complex. AFAICT it is a matter of raw size, not just nesting. I had a grammar that was working fine until I added two new entries, now it's too big. Try repetitions of large mapping rules. I have a set of voice commands for emacs in python mode and one for in lisp mode, where the only difference in the grammar is the number of language keywords supported, where 4 phrases are added to the mapping rule for every keyword. The python one works fine, the lisp one is now too big. They have the same level of nesting.

**Comment by sboosali** [comment]
that's interesting. can you send a link to your two grammars?

On Tuesday, January 27, 2015, jgarvin <notifications@github.com> wrote:

> I've been on rolling my own server/client to use Dragon on Linux (I
> started my project before I know about aenea) and stumbled on this thread
> trying to find if anyone knew the exact conditions that trigger
> natlink.BadGrammar complaining about the grammar being too complex. AFAICT
> it is a matter of raw size, not just nesting. I had a grammar that was
> working fine until I added two new entries, now it's too big. Try
> repetitions of large mapping rules. I have a set of voice commands for
> emacs in python mode and one for in lisp mode, where the only difference in
> the grammar is the number of language keywords supported, where 4 phrases
> are added to the mapping rule for every keyword. The python one works fine,
> the lisp one is now too big. They have the same level of nesting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dictation-toolbox/aenea/issues/19#issuecomment-71723853>
> .
>


-- 



*(this message was composed with dictation: charitably interpret typos)Sam
Boosalis*

**Comment by jgarvin** [comment]
Here's the 128 keyword list for the lisp mode:
https://bpaste.net/show/8d97200e37f9

Note that some elements are lists of two strings rather than a string --
this is for when the spoken and written form should differ.

From the list I would generate a mapping rule that had 4 rules for each
keyword in the list, "future <word> [<n>]", "prior <word> [<n>]", "key
<word>", "new <word>". So there would be 4 * 128 entries -- which being a
power of 2 makes sense as a limit, could be it always dies at 512. It died
when I added the future/prior commands. That was too big apparently.

Moving the keyword list into it's own rule and the 4 possible commands into
their own rule and making the new grammar just "<verb> <word> [<n>]" made
the error go away, which ironically has more possibilities because before
key and new didn't have a number after and now they do.

My guess is Dragon barfs if you try to make an alternative with 512
entries, since I assume that's what MappingRule builds for you.

**Comment by jgarvin** [comment]
Actually, I forgot to subtract out the leading lines, there are only 116
keywords, that the source file containing them was 128 lines is pure luck
:p Still, adding future/prior would have pushed it over 256, which could be
a limit.

**Comment by sboosali** [comment]
I tried a list of 1000 terminals (http://simple.wikipedia.org/wiki/Wikipedia:List_of_1000_basic_words) and both did not throw any bad grammar errors and successfully recognized them when spoken.

Can you reproduce this:

https://bpaste.net/show/aa6c2117c91e

if you drop this file into your MacroSystem folder (that's a NatLink thing, not an Aenea thing), it should disable the other grammars and activate. There are other commented out grammars that should all work too, if you're interested. I think the only problem I had was with a recursive grammar which didn't throw bad grammar error but just crashed Dragon. lol.

The limit might also depend on the system and version and stuff. Like RAM? I'm running Dragon 13 in a VM that has two CPUs and 4 GB of RAM fwiw.

**Comment by sboosali** [comment]
@poppe1219 

this worked for me:

            natlink.recognitionMimic(["Start","spell","mode"])

since it takes a list, not a string: https://github.com/sboosali/NatLink/blob/9545436181f23652224041afa2035f12fa60d949/NatlinkSource/natlink.txt#L209

(another one bites the dust from dynamic types ;)) 

you might need to deactivate your own grammars:

            self.activateSet([], exclusive=0)

or explicitly handle the recognition yourself with:

    def initialize(self):
        self.load(self.gramSpec, allResults=1)
        self.activateSet(["..."], exclusive=1)
        ...

    def gotResultsObject(self, recognitionType, resultsObject):
        if recognitionType == 'other':  # when a different grammar has recognized the utterance, e.g. dragons built-in spelling grammar
        ...
