### ISSUE TITLE
Error when running `aenea/server/linux_x11/test-client.py`

### ISSUE THREAD

**Issue by ericricky** [dictation-toolbox/aenea#197]
I get this output when running `test-client.py`
```
aABBBHello world!Traceback (most recent call last):
  File "test-client.py", line 123, in <module>
    main()
  File "test-client.py", line 118, in main
    test_multiple_actions(communication)
  File "test-client.py", line 102, in test_multiple_actions
    distobj.execute_batch(batch._commands)
  File "test-client.py", line 28, in execute_batch
    self.server.multiple_actions(batch)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 288, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "/usr/local/lib/python2.7/dist-packages/jsonrpclib/jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/home/<...>/aenea/server/core.py", line 64, in patched_rpc_func | TypeError: multiple_actions() takes exactly 2 arguments (1 given)')
```
I had no problems testing `aenea/client/_hello_world_aenea.py`, but I wanted to flag this error since I haven't seen it mentioned.

**Comment by Danesprite** [comment]
I haven't seen this before, thanks for reporting it. In trying to reproduce this, I found a related issue with that test file: an error about the client's security token not being set.

@calmofthestorm I can fix these issues and submit a PR for you to review :-)

**Comment by calmofthestorm** [comment]
I think this has been broken for awhile:/ If you want to fix it that would be great and I could review it. There are a lot of older utilities floating around in the repo that I don't recall the exact purpose or status of (5 year old project that started as a hack, etc). Thanks for helping make it better.

**Comment by Danesprite** [comment]
Yes, I think so too. I should be able to put something together soon.
No problem. I'm happy to fix things like this that get broken.

**Comment by sparkvilla** [comment]
Hi there I am getting the exact same error but differently from @ericricky the test `aenea/client/_hello_world_aenea.py` is not working; i.e. I get `Socket error connecting to aenea server. To avoid slowing dictation, we won't try again for 5 seconds.` on Natlink message. Can somebody help me here?
