### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by edk** [dictation-toolbox/aenea#24]
Having trouble getting this started.  Followed instructions, and installed the packages on an xp virtual box.  I am trying to connect to an Ubuntu 12.04 system.  I think I have the natlink side of things working.

![screen shot 2014-06-28 at 10 54 59 pm](https://cloud.githubusercontent.com/assets/54091/3422619/f6966bb2-ff51-11e3-82ff-24770e042d26.png)

The server seems to start properly when I run it from util: `python server_x11.py`

However, when i start util/aenea.py in the windows vm it exits immediately with a 0 error code.
The experimental aenea_client.py brings up a window, but it doesn't seem to send the data properly to the server.

On the ubuntu server:

``` bash
enea$ python server_x11.py
eddyks-MacBook-Pro.local - - [28/Jun/2014 22:37:28] "POST / HTTP/1.1" 200 -
type: unrecognized option '--file'
Usage: type [--window windowid] [--delay milliseconds] <things to type>
--window <windowid>    - specify a window to send keys to
--delay <milliseconds> - delay between keystrokes
--clearmodifiers       - reset active modifiers (alt, etc) while typing
--args N  - how many arguments to expect in the exec command. This is
            useful for ending an exec and continuing with more xdotool
            commands
--terminator TERM - similar to --args, specifies a terminator that
                    marks the end of 'exec' arguments. This is useful
                    for continuing with more xdotool commands.
-h, --help             - show this help output
eddyks-MacBook-Pro.local - - [28/Jun/2014 22:37:49] "POST / HTTP/1.1" 200 -
```

![screen shot 2014-06-28 at 10 43 57 pm](https://cloud.githubusercontent.com/assets/54091/3422624/6cc05992-ff52-11e3-85c9-04373ef56090.png)

When I'm normal or dictation mode, with the capture window focused, the Dragon dictation dialog pops up.  Then I need to tell it to transfer or manually click it myself.  Is this right?

Thanks for any help getting this going.  It's made more challenging because I'm not familiar with python yet, and I'm in the middle of a worsening rsi episode.

**Comment by Xodarap** [comment]
What version of xdotool should we be using? I see that error but I think I might the newest version:

> demo@ubuntu:~/aenea/server/linux_x11$ xdotool --version
> xdotool version 2.20110530.1

**Comment by calmofthestorm** [comment]
That's a really old version. I'm on:

alexr@autumn:~$ xdotool --version
xdotool version 3.20141006.1

**Comment by mzizzi** [comment]
For what it's worth:

```
$ xdotool --version
xdotool version 3.20140217.1
```

**Comment by Xodarap** [comment]
Thanks! Where are you getting those versions from? The [official website](http://www.semicomplete.com/projects/xdotool/) lists 2011 as the newest version; if I upgrade Ubuntu to the newest then I get up to 2013 but it seems like this release still has some issues.

**Comment by calmofthestorm** [comment]
https://github.com/jordansissel/xdotool
