### ISSUE TITLE
Key translations requires a rethink

### ISSUE THREAD

**Issue by calmofthestorm** [dictation-toolbox/aenea#65]
Right now, the way we handle key translations is less than ideal. The fundamental issue is simple: Dragonfly, Windows, X11, and OS X all use different names for the various keys on the keyboard. We want to make things work with each other as much as possible while avoiding mapping things that aren't equivalent.

Currently, the X11 server maps most Dragonfly keysyms into X11 keysyms. #64 adds a translation layer in the client for < and >. Additionally, Aenea will accept X11 keysyms directly and pass them along to the server.

So the questions I see is:
* Do we need two levels of translation (client and server) or should it entirely be the responsibility of one?
* Should Aenea accept the union of all keys across all platform, just keys for the currently active one (strict and lax do some of this already), or only Dragonfly keys?
  * If only Dragonfly keys, how do we handle platform specific keys (meta, hyper, super, command, etc)?
* Should the client prefer to send Dragonfly symbols, or attempt to translate to the active platform keysyms?

In general, my instinct is it's better for Aenea to pass along anything it can than for it to police what a grammar and the server are allowed to do, insofar as it mediates communication between them. But I do want the same grammar to be able to work across platforms where possible.

My favored solution would probably be to accept union of all platforms on the client, translate all that can be to Dragonfly syms and pass along the rest as are, then the servers translate Dragonfly syms to local platform ones, and executes the rest natively. This means Aenea will let you send a Linux keysym to a Windows server, and the latter will experience an error, but I think this is an acceptable price to pay.

I welcome your thoughts, especially if you have any experience with internationalization and localization -- I've only worked with various layouts of US keyboards, and ideally this would work well for those on other hardware (or at the very least not actively get in their way).

**Comment by mzizzi** [comment]
I think that the aenea server should include the union of keys across all platforms simply for the sake of maintaining a single protocol specification.  Certain key symbols won't make sense on some platforms and that's something that grammar designers will have to deal with.  No amount of mapping will ever make the "command" key make sense on an X11 desktop.  My point here is that some grammars will be inherently platform specific and I imagine that most of aenea's users are developing with a single platform in mind. Servers could detect this and choose to either ignore the bad key symbols or fail the RPC that includes them.

If we really want to enable cross-platform grammars then the grammars themselves should map their actions to key symbols depending on what platform they detect at startup.

**Comment by calmofthestorm** [comment]
Sounds like we have agreement that it should basically be the union, which is what we have now. I agree that any grammar that wishes to work across platforms will need to be platform aware -- my only thought on that topic is that we may wish to make it easy for them to do so. But I agree that the server is not the place for this sort of thing -- it could be exposed client-side as a library grammars can make use of.
