### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by gkz** [dictation-toolbox/aenea#92]
Hello, I have everything set up until testing with `_hello_world_aenea.py`.
I have a winxp vm with the host-only adapter running dragon.

I get an error in the natlink window:
```
Socket error connecting to aenea server. To avoid slowing dictation, we won't try again for 5 seconds.
```
Which is the result of:
```
[Errno 10065] A socket operation was attempted to an unreachable host
```
I have tried many things but have not been able to get the guest to connect to the server.
Any help - exactly what configuration to use for host/port in `config.py` and `aenea.json`, would be appreciated.
Thank you

**Comment by mzizzi** [comment]
Use the address bound to the vboxnet0 interface.

On the linux server machine:
```
$ ifconfig
...
vboxnet0  Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet addr:192.168.56.1  Bcast:192.168.56.255  Mask:255.255.255.0
...
```

aenea.json for the client
```
{
    "host": "192.168.56.1",
    ...
}
```

**Comment by mzizzi** [comment]
An aside: I had very poor results when using xp vms to run dragon.  I saw a significant boost when switching to a win7 vm.  YMMV of course.

**Comment by gkz** [comment]
Thank you for your help.

After many hours, I have found the issue. The default adapter type for the "Host-only Adapter" is "Intel PRO/1000", but this doesn't work with Windows XP, you must choose the "PCnet-FAST III" adapter type. This seems like something Virtualbox should be able to figure out and set, but it doesn't.
